const plots=[
{name:'The Farmhouse',beds:3,rooms:2,bathrooms:'1 + WC',gia:'To be confirmed',form:'Two-storey detached',copy:'A detached home fronting the access road, with a sitting room, kitchen / dining / garden room and three first-floor bedrooms.',image:'farmhouse',drawing:'plot-1',film:3},
{name:'The Stalls',beds:2,rooms:1,bathrooms:'1 shower room',gia:'To be confirmed',form:'Single-storey barn range',copy:'A two-bedroom courtyard home with an open-plan kitchen, dining and sitting room, plus utility storage.',image:'stalls-dairy',drawing:'plots-2-3',film:0},
{name:'The Dairy',beds:2,rooms:1,bathrooms:'1 shower room',gia:'To be confirmed',form:'Single-storey barn range',copy:'A two-bedroom home arranged on one level, with open-plan kitchen, dining and sitting space.',image:'stalls-dairy',drawing:'plots-2-3',film:0},
{name:'The Threshing Barn',beds:4,rooms:2,bathrooms:'2 + WC',gia:'To be confirmed',form:'1½ / two-storey barn design',copy:'A generous four-bedroom barn home with open-plan kitchen and living space, a snug, master suite and threshing-style glazing.',image:'threshing-barn',drawing:'plot-4',film:2},
{name:'The Granary',beds:4,rooms:2,bathrooms:'2 + WC',gia:'To be confirmed',form:'Two-storey barn design',copy:'A four-bedroom courtyard home with open-plan kitchen / dining and sitting / garden rooms, plus a master suite and dressing area.',image:'granary-carthouse',drawing:'plots-5-6',film:1},
{name:'The Carthouse',beds:3,rooms:1,bathrooms:'2 + WC',gia:'To be confirmed',form:'Two-storey barn design',copy:'A three-bedroom home with open-plan kitchen, dining and sitting space, a master suite and external brick stair.',image:'granary-carthouse',drawing:'plots-5-6',film:1}
];
let selected=0,view='visual';
const $=s=>document.querySelector(s);const viewer=$('#viewer'),content=$('#viewer-content'),hero=$('#hero-video'),fox=$('#fox-video');
function render(){const p=plots[selected];$('#home-label').textContent='PLOT '+String(selected+1).padStart(2,'0');$('#home-title').textContent=p.name;$('#home-copy').textContent=p.copy;$('#beds').textContent=p.beds;$('#form').textContent=p.form;$('#rooms').textContent=p.rooms;$('#bathrooms').textContent=p.bathrooms;$('#gia').textContent=p.gia;$('#drawing').src='assets/'+(view==='visual'?p.image+'.webp':p.drawing+'.png');$('#drawing').srcset=view==='visual'?`assets/${p.image}-640.webp 640w, assets/${p.image}-1024.webp 1024w, assets/${p.image}.webp ${p.image==='threshing-barn'?1694:p.image==='stalls-dairy'?1721:1672}w`:'';$('#drawing').alt='Plot '+(selected+1)+' · '+p.name+' · '+(view==='visual'?'Architectural visualisation':'Floor plans and elevations');$('#drawing-open').classList.toggle('is-plan',view==='drawing');$('#drawing-download').href='assets/'+p.drawing+'.pdf';$('#plot-enquire').href='mailto:contact@foxvisiondesign.co.uk?subject='+encodeURIComponent('Rose Cottage Fold — Plot '+(selected+1)+' '+p.name);document.querySelectorAll('.home-switch button').forEach(b=>{const active=Number(b.dataset.plot)===selected;b.classList.toggle('active',active);b.setAttribute('aria-pressed',active)});document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.view===view));const video=$('#home-video');video.pause();$('#drawing-open').hidden=view==='video';video.hidden=view!=='video';$('#drawing-note').hidden=view!=='drawing';if(view==='video'){video.src='assets/film-'+p.film+'.mp4';video.poster='assets/'+p.image+'.webp'}document.dispatchEvent(new Event('plotchange'));}
document.querySelectorAll('[data-plot]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();openHome(Number(b.dataset.plot))}));document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{view=b.dataset.view;render();if(view==='drawing')show('assets/'+plots[selected].drawing+'.png',plots[selected].name+' · Plans and elevations')}));
let lightboxNavigator=null;
function show(src,caption,isVideo=false){
 lightboxNavigator?.destroy();lightboxNavigator=null;content.replaceChildren();content.classList.remove('zoomed');
 const drawingName=src.match(/(?:^|\/)(plot-1|plots-2-3|plot-4|plots-5-6)(?:-full)?\.(?:png|pdf)(?:\?.*)?$/)?.[1];
 const fullSrc=drawingName?'assets/'+drawingName+'-full.png':src.replace(/\.webp(?:\?.*)?$/,'-original.png');
 const media=document.createElement(isVideo?'video':'img');media.src=isVideo?src:fullSrc;
 viewer.classList.toggle('drawing-viewer',Boolean(drawingName));
 if(isVideo){media.controls=true;media.playsInline=true;media.preload='metadata';content.append(media)}
 else{
  media.alt=caption;media.draggable=false;const wrap=document.createElement('div');wrap.className='lightbox-wrap';const stage=document.createElement('div');stage.className='image-stage lightbox-stage';stage.tabIndex=0;stage.setAttribute('role','region');stage.setAttribute('aria-label','Image viewer. Plus and minus zoom; arrow keys pan; Home resets.');const layer=document.createElement('div');layer.className='image-layer';layer.append(media);stage.append(layer);const controls=document.createElement('div');controls.className='lightbox-controls';
  const add=(label,aria,fn)=>{const b=document.createElement('button');b.type='button';b.textContent=label;b.setAttribute('aria-label',aria);b.addEventListener('click',fn);controls.append(b)};
  add('−','Zoom out',()=>lightboxNavigator?.zoomOut());add('+','Zoom in',()=>lightboxNavigator?.zoomIn());add('Reset','Reset image',()=>lightboxNavigator?.reset());
  if(drawingName){const pdfButton=document.createElement('button');pdfButton.type='button';pdfButton.textContent='View original PDF';pdfButton.addEventListener('click',()=>{lightboxNavigator?.destroy();lightboxNavigator=null;const frame=document.createElement('iframe');frame.className='inline-pdf';frame.src='assets/'+drawingName+'.pdf#view=FitH';frame.title=caption+' · Original PDF';frame.setAttribute('loading','eager');stage.replaceChildren(frame);stage.classList.add('pdf-stage');controls.querySelectorAll('button').forEach(button=>button.hidden=true);const back=document.createElement('button');back.type='button';back.textContent='Back to zoomable plan';back.addEventListener('click',()=>show('assets/'+drawingName+'.png',caption));controls.append(back);});controls.append(pdfButton)}else{const original=document.createElement('a');original.href=fullSrc;original.textContent='Open original ↗';original.target='_blank';original.rel='noopener';controls.append(original)}wrap.append(stage,controls);content.append(wrap);
  lightboxNavigator=createImageNavigator(stage,layer,{maxZoom:10,wheelZoom:true});const loaded=()=>lightboxNavigator?.setImage(media.naturalWidth,media.naturalHeight);media.addEventListener('load',loaded,{once:true});media.addEventListener('error',()=>{stage.textContent='The image could not load. Please open the original file below.';stage.setAttribute('role','status')},{once:true});if(media.complete&&media.naturalWidth)loaded();
 }
 $('#viewer-caption').textContent=caption+(isVideo?'':' · Pinch to zoom · Drag to move');hero.pause();fox.pause();$('#home-video').pause();if(!viewer.open)viewer.showModal();document.body.classList.add('viewer-open');lightboxNavigator?.resize();if(isVideo)media.play().catch(()=>{});
}
document.querySelectorAll('[data-image]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.image,b.dataset.caption)));document.querySelectorAll('[data-film]').forEach(b=>b.addEventListener('click',()=>show('assets/film-'+b.dataset.film+'.mp4',b.dataset.caption,true)));$('#drawing-open').addEventListener('click',()=>show($('#drawing').src,$('#drawing').alt));$('#plot-film').addEventListener('click',()=>show('assets/film-'+plots[selected].film+'.mp4',plots[selected].name+' · Architectural film',true));$('.close').addEventListener('click',()=>viewer.close());viewer.addEventListener('close',()=>{lightboxNavigator?.destroy();lightboxNavigator=null;content.querySelector('video')?.pause();content.replaceChildren();document.body.classList.remove('viewer-open')});viewer.addEventListener('click',e=>{if(e.target===viewer)viewer.close()});
const menu=$('.menu-toggle'),nav=$('#main-nav');menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',open);nav.classList.toggle('is-open',open)});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{menu.setAttribute('aria-expanded','false');nav.classList.remove('is-open')}));document.addEventListener('keydown',e=>{if(e.key==='Escape'){menu.setAttribute('aria-expanded','false');nav.classList.remove('is-open')}});
function sync(video,button){const paused=video.paused;button.textContent=paused?'▶':'Ⅱ';button.setAttribute('aria-label',paused?'Play film':'Pause film');button.setAttribute('title',paused?'Play':'Pause')}
for(const [video,button] of [[hero,$('#pause')],[fox,$('#fox-play')]]){button.addEventListener('click',()=>{if(video.paused)video.play().catch(()=>{});else video.pause()});video.addEventListener('play',()=>sync(video,button));video.addEventListener('pause',()=>sync(video,button));video.addEventListener('error',()=>{button.hidden=true})}
$('#fox-full').addEventListener('click',()=>show('assets/fox-land-story.mp4','FOX · Every piece of land has a story',true));
if(!matchMedia('(prefers-reduced-motion: reduce)').matches&&!navigator.connection?.saveData)hero.play().catch(()=>{});
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(!e.isIntersecting)e.target.pause()}),{threshold:.1});observer.observe(hero);observer.observe(fox);document.addEventListener('visibilitychange',()=>{if(document.hidden){hero.pause();fox.pause();content.querySelector('video')?.pause();$('#home-video').pause()}});

const homeDialog=$('#home-dialog');
function openHome(index){selected=index;view='visual';render();hero.pause();fox.pause();if(!homeDialog.open)homeDialog.showModal();document.body.classList.add('home-open');homeDialog.scrollTop=0;}
$('#home-close').addEventListener('click',()=>homeDialog.close());
homeDialog.addEventListener('close',()=>{$('#home-video').pause();document.body.classList.remove('home-open')});
homeDialog.addEventListener('click',e=>{if(e.target===homeDialog)homeDialog.close()});
document.querySelectorAll('.home-switch button').forEach((b,i)=>{const p=plots[i];b.removeAttribute('aria-pressed');b.classList.remove('active');b.setAttribute('aria-haspopup','dialog');b.setAttribute('aria-controls','home-dialog');b.innerHTML=`<img src="assets/${p.image}-640.webp" alt="${p.name} architectural visualisation" loading="lazy"><span class="home-card-copy"><small>PLOT ${String(i+1).padStart(2,'0')} · ${p.beds} BEDROOMS</small><strong>${p.name}</strong><span>Explore home ↗</span></span>`;});

const enquiryDialog=$('#enquiry-dialog'),enquiryForm=$('#enquiry-form');
document.querySelectorAll('[data-enquire]').forEach(button=>button.addEventListener('click',()=>enquiryDialog.showModal()));
enquiryDialog.querySelector('.enquiry-close').addEventListener('click',()=>enquiryDialog.close());
enquiryDialog.addEventListener('click',event=>{if(event.target===enquiryDialog)enquiryDialog.close()});
function enquiryMessage(){const data=new FormData(enquiryForm);return{subject:'Rose Cottage Fold — '+data.get('interest'),body:['Name: '+data.get('name'),'Email: '+data.get('email'),'Phone: '+(data.get('phone')||'Not provided'),'Interested in: '+data.get('interest'),'','Message:',data.get('message')].join('\r\n')}}
enquiryForm.addEventListener('submit',event=>{event.preventDefault();if(!enquiryForm.reportValidity())return;const message=enquiryMessage();const gmail='https://mail.google.com/mail/?view=cm&fs=1&to='+encodeURIComponent('contact@foxvisiondesign.co.uk')+'&su='+encodeURIComponent(message.subject)+'&body='+encodeURIComponent(message.body);const opened=window.open(gmail,'_blank');if(opened)opened.opener=null;$('#enquiry-status').textContent=opened?'Your completed message has opened in Gmail. Review it and press Send.':'Your browser blocked the new tab. Please select “Use another email app” below.'});
$('#enquiry-mailto').addEventListener('click',event=>{if(!enquiryForm.reportValidity()){event.preventDefault();return}const message=enquiryMessage();event.currentTarget.href='mailto:contact@foxvisiondesign.co.uk?subject='+encodeURIComponent(message.subject)+'&body='+encodeURIComponent(message.body)});

// Every architectural drawing entry point uses the same full-screen viewer.
for(const id of ['drawing-download']){
 const link=document.getElementById(id);link.setAttribute('aria-haspopup','dialog');
 link.addEventListener('click',event=>{event.preventDefault();show(link.href,plots[selected].name+' · Plans and elevations')});
}
document.getElementById('plan-original').addEventListener('click',event=>{event.preventDefault();show(event.currentTarget.href,document.getElementById('plan-mode-label').textContent)});
