/* Shared image navigation: preserves image geometry and supports touch, mouse and keyboard. */
function createImageNavigator(stage,layer,{onUpdate=()=>{},maxZoom=5,wheelZoom=false}={}){
 let iw=1,ih=1,base=1,zoom=1,x=0,y=0,disposed=false,dragged=false;
 const points=new Map(),listeners=[];
 const bind=(el,event,fn,opts)=>{el.addEventListener(event,fn,opts);listeners.push(()=>el.removeEventListener(event,fn,opts))};
 function clamp(){const w=stage.clientWidth,h=stage.clientHeight;const mx=Math.max(0,(iw*base*zoom-w)/2),my=Math.max(0,(ih*base*zoom-h)/2);x=Math.max(-mx,Math.min(mx,x));y=Math.max(-my,Math.min(my,y));}
 function draw(){if(disposed)return;clamp();layer.style.width=iw*base+'px';layer.style.height=ih*base+'px';layer.style.left=(stage.clientWidth-iw*base)/2+'px';layer.style.top=(stage.clientHeight-ih*base)/2+'px';layer.style.transform=`translate(${x}px,${y}px) scale(${zoom})`;layer.style.setProperty('--inverse-zoom',1/zoom);onUpdate(zoom);}
 function fit(){base=Math.min(stage.clientWidth/iw,stage.clientHeight/ih);draw()}
 function reset(){zoom=1;x=y=0;fit()}
 function setImage(w,h){iw=w;ih=h;reset()}
 function zoomAt(value,cx=stage.clientWidth/2,cy=stage.clientHeight/2){const next=Math.max(1,Math.min(maxZoom,value)),r=next/zoom;const ax=cx-stage.clientWidth/2,ay=cy-stage.clientHeight/2;x=ax-(ax-x)*r;y=ay-(ay-y)*r;zoom=next;draw()}
 const local=e=>{const r=stage.getBoundingClientRect();return {x:e.clientX-r.left,y:e.clientY-r.top}};
 bind(stage,'pointerdown',e=>{if(e.target.closest('button,a'))return;if(e.pointerType==='mouse'&&e.button!==0)return;const p=local(e);points.set(e.pointerId,p);dragged=false;stage.setPointerCapture(e.pointerId);stage.classList.add('is-dragging')});
 bind(stage,'pointermove',e=>{if(!points.has(e.pointerId))return;const old=points.get(e.pointerId),p=local(e);if(Math.hypot(p.x-old.x,p.y-old.y)>2)dragged=true;
 if(points.size===2){const other=[...points.entries()].find(([id])=>id!==e.pointerId)?.[1];if(other){const before=Math.hypot(old.x-other.x,old.y-other.y),after=Math.hypot(p.x-other.x,p.y-other.y);if(before>0)zoomAt(zoom*after/before,(p.x+other.x)/2,(p.y+other.y)/2);x+=(p.x-old.x)/2;y+=(p.y-old.y)/2;}}
 else{x+=p.x-old.x;y+=p.y-old.y;}points.set(e.pointerId,p);draw()});
 const release=e=>{points.delete(e.pointerId);if(!points.size)stage.classList.remove('is-dragging')};bind(stage,'pointerup',release);bind(stage,'pointercancel',release);bind(stage,'lostpointercapture',release);
 bind(stage,'wheel',e=>{if(!wheelZoom&&!e.ctrlKey&&!e.metaKey)return;e.preventDefault();const p=local(e);zoomAt(zoom*Math.exp(-e.deltaY*.008),p.x,p.y)},{passive:false});
 bind(stage,'dblclick',e=>{if(e.target.closest('button,a'))return;const p=local(e);zoomAt(zoom>1?1:2,p.x,p.y)});
 bind(stage,'keydown',e=>{if(e.target!==stage)return;const actions={'+':()=>zoomAt(zoom*1.3),'=':()=>zoomAt(zoom*1.3),'-':()=>zoomAt(zoom/1.3),'Home':reset,'ArrowLeft':()=>{x+=65;draw()},'ArrowRight':()=>{x-=65;draw()},'ArrowUp':()=>{y+=65;draw()},'ArrowDown':()=>{y-=65;draw()}};if(actions[e.key]){e.preventDefault();actions[e.key]()}});
 const ro=new ResizeObserver(fit);ro.observe(stage);
 return {setImage,reset,resize:fit,zoomIn:()=>zoomAt(zoom*1.35),zoomOut:()=>zoomAt(zoom/1.35),destroy(){disposed=true;ro.disconnect();listeners.forEach(f=>f());points.clear()}};
}

(()=>{
 const configs={plan:{src:'site-plan',size:[2048,1185],label:'2D architectural site plan',pins:[[38.5,55.8],[57.8,57.5],[70,59],[85,48.5],[63.9,33.3],[51.6,26.4]]},aerial:{src:'aerial',size:[1672,941],label:'3D aerial visualisation · Arrival view',pins:[[75.7,53],[45.5,27.5],[34.8,17.7],[22.8,10.8],[14.4,31],[24.1,48.8]]},reverse:{src:'aerial-reverse',size:[1672,941],label:'3D aerial visualisation · Courtyard view',pins:[[14.6,17.5],[29.7,36],[46.5,54],[79,66],[54,20],[42.5,12.5]]}};
 const host=document.querySelector('#interactive-plan'),stage=document.querySelector('#plan-stage'),layer=document.querySelector('#plan-layer'),img=document.querySelector('#plan-image'),pins=document.querySelector('#plan-pins'),dialog=document.querySelector('#plan-dialog');let mode='plan',angle='aerial';
 const nav=createImageNavigator(stage,layer,{onUpdate:z=>{document.querySelector('#plan-zoom').textContent=Math.round(z*100)+'%';document.querySelector('#plan-minus').disabled=z<=1.001;document.querySelector('#plan-plus').disabled=z>=4.999}});
 const home=host.parentNode,marker=document.createComment('interactive plan position');home.insertBefore(marker,host);
 plots.forEach((p,i)=>{const b=document.createElement('button');b.className='plot-pin';b.type='button';b.textContent=String(i+1).padStart(2,'0');b.setAttribute('aria-label',`Plot ${i+1}: ${p.name}, ${p.beds} bedrooms`);b.title='Explore '+p.name;b.dataset.home=p.name;b.addEventListener('click',()=>selectPlot(i));pins.append(b)});
 function selectPlot(i){selected=i;render();updateCard();const card=document.querySelector('.plan-card');card.classList.remove('plot-selected');requestAnimationFrame(()=>card.classList.add('plot-selected'))}
 function updateCard(){const p=plots[selected];document.querySelector('#plan-plot-label').textContent='PLOT '+String(selected+1).padStart(2,'0');document.querySelector('#plan-plot-name').textContent=p.name;document.querySelector('#plan-plot-spec').textContent=p.form;document.querySelector('#plan-plot-copy').textContent=p.copy;document.querySelector('#plan-bedrooms').textContent=p.beds;document.querySelector('#plan-rooms').textContent=p.rooms;document.querySelector('#plan-bathrooms').textContent=p.bathrooms;document.querySelector('#plan-gia').textContent=p.gia;const photo=document.querySelector('#plan-plot-photo');photo.src='https://rose-cottage-courtyard.dobermanast.chatgpt.site/assets/'+p.image+'.webp';photo.srcset=`https://rose-cottage-courtyard.dobermanast.chatgpt.site/assets/${p.image}-640.webp 640w, https://rose-cottage-courtyard.dobermanast.chatgpt.site/assets/${p.image}-1024.webp 1024w, https://rose-cottage-courtyard.dobermanast.chatgpt.site/assets/${p.image}.webp ${p.image==='threshing-barn'?1694:p.image==='stalls-dairy'?1721:1672}w`;photo.alt=p.name+' architectural visualisation';document.querySelector('#plan-plot-select').value=selected;document.querySelector('#plan-plot-pdf').href='https://rose-cottage-courtyard.dobermanast.chatgpt.site/assets/'+p.drawing+'.pdf';pins.querySelectorAll('button').forEach((b,i)=>b.setAttribute('aria-pressed',i===selected));}
 function switchView(next){mode=next;const c=configs[mode==='plan'?'plan':angle];img.src='https://rose-cottage-courtyard.dobermanast.chatgpt.site/assets/'+c.src+'-original.png';img.alt=c.label;nav.setImage(...c.size);document.querySelector('#plan-mode-label').textContent=c.label;document.querySelector('#plan-angle').hidden=mode==='plan';document.querySelector('#plan-original').href='https://rose-cottage-courtyard.dobermanast.chatgpt.site/assets/'+c.src+'-original.png';pins.querySelectorAll('button').forEach((b,i)=>{b.style.left=c.pins[i][0]+'%';b.style.top=c.pins[i][1]+'%'});document.querySelectorAll('[data-plan-mode]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.planMode===mode));}
 document.querySelectorAll('[data-plan-mode]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.planMode)));
 document.querySelector('#plan-angle').addEventListener('click',()=>{angle=angle==='aerial'?'reverse':'aerial';switchView('aerial')});
 document.querySelector('#plan-plus').addEventListener('click',nav.zoomIn);document.querySelector('#plan-minus').addEventListener('click',nav.zoomOut);document.querySelector('#plan-reset').addEventListener('click',nav.reset);
 document.querySelector('#plan-plot-select').addEventListener('change',e=>selectPlot(Number(e.target.value)));
 document.querySelector('#plan-plot-cgi').addEventListener('click',()=>show('https://rose-cottage-courtyard.dobermanast.chatgpt.site/assets/'+plots[selected].image+'.webp',plots[selected].name+' · CGI visualisation'));
 document.querySelector('#plan-plot-floor').addEventListener('click',()=>show('https://rose-cottage-courtyard.dobermanast.chatgpt.site/assets/'+plots[selected].drawing+'.png',plots[selected].name+' · Floor plans and elevations'));
 document.querySelector('#plan-plot-video').addEventListener('click',()=>show('https://rose-cottage-courtyard.dobermanast.chatgpt.site/assets/film-'+plots[selected].film+'.mp4',plots[selected].name+' · Architectural film',true));
 const expand=document.querySelector('#plan-expand');expand.addEventListener('click',()=>{if(dialog.open){dialog.close();return}dialog.append(host);dialog.showModal();document.body.classList.add('plan-expanded');expand.textContent='Close full screen ×';expand.setAttribute('aria-expanded','true');nav.resize();expand.focus()});
 dialog.addEventListener('close',()=>{marker.after(host);document.body.classList.remove('plan-expanded');expand.textContent='Full screen ⤢';expand.setAttribute('aria-expanded','false');nav.resize();expand.focus()});
 document.addEventListener('plotchange',updateCard);switchView('plan');updateCard();
})();
